backend:
  name: test-repo

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - label: "Главная"
        name: "home"
        file: "index.html"
        fields:
          - { label: "HTML", name: "body", widget: "text" }
