backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "gallery"
    label: "Галерея"
    files:
      - label: "Список фото"
        name: "gallery"
        file: "gallery.json"
        format: "json"
        fields:
          - label: "Фото"
            name: "items"
            widget: "list"
            fields:
              - { label: "Название", name: "title", widget: "string" }
              - { label: "Картинка", name: "image", widget: "image" }
              - { label: "Описание", name: "desc", widget: "string", required: false }
